# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminweb',
            options={'verbose_name': 'Admin web', 'verbose_name_plural': 'Admins web'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de usuário', 'verbose_name_plural': 'Perfis de usuário'},
        ),
        migrations.AlterModelOptions(
            name='tipoobjeto',
            options={'verbose_name': 'Tipo de objeto', 'verbose_name_plural': 'Tipos de objeto'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='objeto',
            name='codigo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nome',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoobjeto',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
