# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='reservaInicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='resevaFim',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='devolucao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='retirada',
            field=models.DateTimeField(null=True),
        ),
    ]
