# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
