# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0002_auto_20171021_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='resevaFim',
            new_name='reservaFim',
        ),
    ]
