# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0002_auto_20170914_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminweb',
            options={'verbose_name': 'Admin web', 'verbose_name_plural': 'Admins web'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de usuário', 'verbose_name_plural': 'Perfis de usuário'},
        ),
        migrations.AlterModelOptions(
            name='tipoobjeto',
            options={'verbose_name': 'Tipo de objeto', 'verbose_name_plural': 'Tipos de objeto'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
