# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0003_auto_20170915_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='codigo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
