# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0003_auto_20171021_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'permissions': (('can_see_details_movement', 'Can see details Movimentacao'), ('can_back_objeto', 'Can set give back Objeto')), 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
    ]
