# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0003_auto_20170915_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.IntegerField(blank=True, choices=[(3, 'Solicitado Devolução'), (2, 'Emprestado'), (5, 'Solicitado Transferência'), (6, 'Transferência confirmada'), (7, 'Solicitado Reserva'), (1, 'Solicitado retirada'), (4, 'Devolvido'), (8, 'Reserva confirmada')], default=0, null=True),
        ),
    ]
