# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0004_auto_20171023_1853'),
        ('ces', '0004_auto_20171023_0908'),
    ]

    operations = [
    ]
