# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0004_auto_20170921_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='nome',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoobjeto',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
