# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0005_merge_20171025_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'permissions': (('can_see_details', 'Can see details Movimentacao'), ('can_mark_retired', 'Set Objeto as retired'), ('can_mark_returned', 'Set Objeto as returned')), 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='objeto',
            options={'verbose_name': 'Objeto', 'verbose_name_plural': 'Objetos'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Solicitado Retirada'), (2, 'Emprestado'), (3, 'Solicitado Devolução'), (4, 'Devolvido'), (8, 'Solicitado Reserva')], default=0),
        ),
        migrations.AddField(
            model_name='objeto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Indisponível'), (3, 'Pendente')], default=1),
        ),
    ]
