# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0006_auto_20171012_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
            },
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='perfilUsuario_id',
            new_name='profileName',
        ),
        migrations.AddField(
            model_name='objeto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Emprestado'), (3, 'Pendente')], default=1),
        ),
        migrations.AddField(
            model_name='tipoobjeto',
            name='icone',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitado Retirada'), (2, 'Emprestado'), (3, 'Solicitado Devolução'), (4, 'Devolvido'), (5, 'Solicitado Transferência'), (6, 'Transferência Pendente'), (7, 'Transferência Confirmada'), (8, 'Solicitado Reserva')]),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='ces.Movimentacao'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='ces.Movimentacao'),
        ),
    ]
