# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 10:17
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0006_auto_20171025_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoobjeto',
            name='icone',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
