# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0008_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitado Retirada'), (2, 'Emprestado'), (3, 'Solicitado Devolução'), (4, 'Devolvido'), (5, 'Solicitado Transferência'), (6, 'Transferência Pendente'), (7, 'Transferência Confirmada'), (8, 'Solicitado Reserva')], default=0),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Indisponível'), (3, 'Pendente')], default=1),
        ),
    ]
