# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0010_auto_20171013_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Solicitado Retirada'), (2, 'Emprestado'), (3, 'Solicitado Devolução'), (4, 'Devolvido'), (5, 'Solicitado Transferência'), (6, 'Transferência Pendente'), (7, 'Transferência Confirmada'), (8, 'Solicitado Reserva')], default=0),
        ),
    ]
