# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ces', '0011_auto_20171013_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='movimentacao_id_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_id_destino', to='ces.Movimentacao'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='movimentacao_id_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_id_origem', to='ces.Movimentacao'),
        ),
    ]
